<a href="https://colab.research.google.com/github/Anithatangirala/Oasis_Infobyte-Task-4/blob/main/Oasis_Infobyte_Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [ ]:
df.drop_duplicates()
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [ ]:
df=df.drop(columns =['name','neighbourhood','calculated_host_listings_count'])
df.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,LisaRoxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   48895 non-null  int64
 1   host_id              48895 non-null  int64
 2   host_name            48874 non-null  object
 3   neighbourhood_group  48895 non-null  object
 4   latitude             48895 non-null  float64
 5   longitude            48895 non-null  float64
 6   room_type            48895 non-null  object
 7   price                48895 non-null  int64
 8   minimum_nights       48895 non-null  int64
 9   number_of_reviews    48895 non-null  int64
 10  last_review          38843 non-null  object
 11  reviews_per_month    38843 non-null  float64
 12  availability_365     48895 non-null  int64
dtypes: float64(3), int64(6), object(4)
memory usage: 4.8+ MB

In [ ]:
#converting data type and removing nan values
df['host_name'] = df['host_name'].astype(str)
df['host_name'] = df['host_name'].str.replace('nan','')
#removing all non alphabetical characters
df['host_name'] = df['host_name'].str.replace('[^a-zA-Z]','',regex=True)
#Creating space between any 2 names
df['host_name'] = df['host_name'].str.replace(r'([a-z])([A-Z])',r'\1 \2',regex=True)
df.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,0

In [ ]:
df_priced = df[df['price']!= 0]
df_priced.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,0

In [ ]:
df_year = df[df['minimum_nights']<= 367]
df_year.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,0

In [ ]:
df_available = df[df['availability_365']!=0]
df_available.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,194
5,5099,7322,Chris,Manhattan,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,129

CLEANING LAST_REVIEW COLUMN

In [ ]:
#converting data type into string
df['last_review'] = df['last_review'].astype(str)
df['last_review'] = df['last_review'].str.replace('nan',' ')
df.head()

,id,host_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,availability_365
0,2539,2787,John,Brooklyn,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,365
1,2595,2845,Jennifer,Manhattan,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,355
2,3647,4632,Elisabeth,Manhattan,40.80902,-73.94190,Private room,150,3,0,,NaN,365
3,3831,4869,Lisa Roxanne,Brooklyn,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,194
4,5022,7192,Laura,Manhattan,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,0